DROP TABLE GROUPBOARD;

CREATE TABLE GROUPBOARD(
    GBID NUMBER(10) PRIMARY KEY,
    GDID NUMBER(6) NOT NULL,
    MID VARCHAR2(1000) NOT NULL,
    GBCONTENT VARCHAR2(4000),
    GBFILENAME VARCHAR2(1000),
    GBRDATE TIMESTAMP DEFAULT SYSDATE 
);
DROP SEQUENCE GROUPBOARD_SEQ;

CREATE SEQUENCE GROUPBOARD_SEQ NOCYCLE NOCACHE;

COMMIT;

INSERT INTO GROUPBOARD(GBID, GDID, MID, GBCONTENT, GBFILENAME)
    VALUES(GROUPBOARD_SEQ.NEXTVAL, 100, 'QER2735', '대화1', NULL);
    
INSERT INTO GROUPBOARD(GBID, GDID, MID, GBCONTENT, GBFILENAME)
    VALUES(GROUPBOARD_SEQ.NEXTVAL, 100, 'WNSRLF', '대화2', NULL);
        
INSERT INTO GROUPBOARD(GBID, GDID, MID, GBCONTENT, GBFILENAME)
    VALUES(GROUPBOARD_SEQ.NEXTVAL, 200, 'QER2735', '대화3', NULL);
            
INSERT INTO GROUPBOARD(GBID, GDID, MID, GBCONTENT, GBFILENAME)
    VALUES(GROUPBOARD_SEQ.NEXTVAL, 200, 'KIM123', '대화4', NULL);
            
SELECT * FROM GROUPBOARD;        

-- 대화 입력 
INSERT INTO GROUPBOARD(GBID, GDID, MID, GBCONTENT, GBFILENAME)
    VALUES(GROUPBOARD_SEQ.NEXTVAL, 100, 'QER2735', '대화1', NULL);

-- 대화 삭제 
DELETE FROM GROUPBOARD WHERE GBID = 37;

-- 그룹별 대화 내역 출력(최근 10개 최근게시글 아래로)
SELECT *
    FROM(SELECT ROWNUM RN2, GB.* 
            FROM (SELECT ROWNUM RN, GROUPBOARD.* 
                    FROM GROUPBOARD 
                    WHERE GDID = 100 ORDER BY GBID DESC)GB
            ORDER BY RN2 DESC) 
    WHERE RN2 BETWEEN 1 AND 10;

-- 그룹별 과거 대화내역 가져오기 10개씩 
-- SERVICE단에서 RN2 BETWEEN 11 AND 20 수정하여 받음 
-- 클릭할때마다? SESSION값에 과거보기 1 추가
SELECT *
    FROM(SELECT ROWNUM RN2, GB.* 
            FROM (SELECT ROWNUM RN, GROUPBOARD.* 
                    FROM GROUPBOARD 
                    WHERE GDID = 100 ORDER BY GBID DESC)GB
            ORDER BY RN2 DESC) 
    WHERE RN2 BETWEEN 11 AND 20;

-- 대화글 하나 가져오기? //주기적으로 대화 최신화 
-- 대화글 리스트로 받아서 기존글 ID와 비교 ?
SELECT * FROM GROUPBOARD WHERE GDID = 100 ORDER BY GBID DESC;









        